### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by BangKuntet** [TheCaduceus/CloneBot_V2#32]
i done make bot clone but why bot doesnt work when i /sa

or in github fork i must upload folder accounts with json all files???

**Comment by TheCaduceus** [comment]
@BangKuntet Provide Screenshot.

**Comment by missemily2022** [comment]
@BangKuntet Provide Proof so that we may solve your query

**Comment by BangKuntet** [comment]
done i watch tutorial in youtube its help me

sorry i newbie but now bot is working and fine
