### ISSUE TITLE
Can I use service account to copy from a Google Drive to Microsoft Onedrive?

### ISSUE THREAD

**Issue by emersonjr** [TheCaduceus/CloneBot_V2#49]
Is there any way to use this method and have this larger daily upload/download limit to copy from a Google Drive to a Microsoft One Drive?

Thanks in advance for this great work.

**Comment by TheCaduceus** [comment]
@emersonjr Yup! you can use Service Accounts to copy data from Google Drive to OneDrive or anyother cloud for bypassing 10TB Download limit of Google Drive for each account, but you need to use other tools except CloneBot V2 because it only copy files in Google Drive..
