### ISSUE TITLE
Some statistic data not changing while copying in progress

### ISSUE THREAD

**Issue by emersonjr** [TheCaduceus/CloneBot_V2#50]
I had the Readme screenshot as an example of what I would see exactly when doing here on my side, but actually for me it executed as the screenshot below. No Speed, no ETA, no Size, no Checks stats, only Transfers and Progress bar did show some "progress" throughout the process. Is it supposed to be regular or is there any little issue? Not a real trouble, since copying was accomplished.

![image](https://user-images.githubusercontent.com/8794425/184463477-084dffb6-d6c3-470e-8da4-1ca47f859fc9.png)

**Comment by TheCaduceus** [comment]
**@emersonjr It is because newer gclone builds not gives any estimate for a single file! it can be fixed if you deploy bot using Docker.**
