### ISSUE TITLE
Failed deploy on VPS

### ISSUE THREAD

**Issue by vishnoe115** [TheCaduceus/CloneBot_V2#52]
Try deploying on oracle ubuntu 22.04 VPS with given tutorial,, in the end it said **Gclone Executable was not found in the Drectory.** even though gclone file already in directory  **telegram_gcloner/gclone** how to fix this? 

edit config.ini directly **telegram_gcloner/config.ini**

any suggestion?

```
2022-08-24 16:12:17,230 - utils.config_loader - INFO - Found path_to_gclone: gclone
2022-08-24 16:12:17,230 - utils.config_loader - INFO - Found gclone_para_override: 
2022-08-24 16:12:17,230 - utils.config_loader - WARNING - Gclone Executable was not found in the Drectory.
Press Enter to continue...
```

**Comment by TheCaduceus** [comment]
@vishnoe115 **Change `path_to_gclone` to `./gclone` and if problem still persist then run `chmod +x ./gclone` before running the CloneBot V2.**

**Comment by vishnoe115** [comment]
> @vishnoe115 **Change `path_to_gclone` to `./gclone` and if problem still persist then run `chmod +x ./gclone` before running the CloneBot V2.**
still not working.  thanks for your response.

![image](https://user-images.githubusercontent.com/54537571/186474198-80384c1a-68bd-4590-bba8-de4763080940.png)

**Comment by TheCaduceus** [comment]
@vishnoe115 **Did you downloaded gclone from website?**

**Comment by vishnoe115** [comment]
> @vishnoe115 **Did you downloaded `gclone` from website into `telegram_gcloner` folder?**

yes exactly as your given link at readme.
`curl https://clonebot.tk/0:/In%20Use/gclone >> telegram_gcloner/gclone`

**Comment by vishnoe115** [comment]
Update,
already working bro. my bad, forgot to provide full path. nice repo thank you
`path_to_gclone: /home/ubuntu/clonebot/telegram_gcloner/gclone`

**Comment by TheCaduceus** [comment]
@vishnoe115 🤦 No problem! Thanks

**Comment by vishnoe115** [comment]
bro sorry to disturb again, I just try using clone today, and got like this when try to cloning, do have any suggestion to fix? 
I run this in oracle VPS arm64/v8

```
 /usr/local/lib/python3.10/dist-packages/telegram/ext/filters.py:198: TelegramDeprecationWarning: Filters.private is deprecated. Use Filters.chat_type.private instead.
   return self.filter(update.effective_message)
 2022-08-25 21:37:32,925 - handlers.sa - INFO - 100 service account files have been saved for 222299348.
 /usr/local/lib/python3.10/dist-packages/telegram/ext/filters.py:198: TelegramDeprecationWarning: Filters.group is deprecated. Use Filters.chat_type.groups instead.
  return self.filter(update.effective_message)
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
     self.run()
  File "/usr/src/app/telegram_gcloner/utils/fire_save_files.py", line 95, in run
     process = subprocess.Popen(command_line,
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
     self._execute_child(args, executable, preexec_fn, close_fds,
   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
 OSError: [Errno 8] Exec format error: './gclone'
```
