### ISSUE TITLE
fly.io deploy Error? "WARNING Can't find General section in the Config File ."

### ISSUE THREAD

**Issue by erickyun** [TheCaduceus/CloneBot_V2#56]
Hi,

I'm having this problem when I try to deploy it on fly.io ?

![error ss](https://user-images.githubusercontent.com/71968711/187045200-286e0ce1-a2dc-47ab-bfa9-f4c5ba98f3c5.jpg)

**Comment by TheCaduceus** [comment]
Provide `CONFIG_FILE_URL` in `.toml` file, or if its happening after providing the value correctly then you did mistake in `config.ini`, refer to `sample-config.ini` for right format.
