### ISSUE TITLE
Bot can't detect gclone in VPS

### ISSUE THREAD

**Issue by RitZz48** [TheCaduceus/CloneBot_V2#58]
Hey, 

When I try to run Clonebot in a Linux VPS and try to clone something the log says File not found "gclone" 
![image](https://user-images.githubusercontent.com/102799834/187267846-6bfc5115-c6b1-4c70-80aa-256c030bd3bb.png)

but there is gclone installed on the system. Here's what I see when I ls in telegram_gcloner folder
![image](https://user-images.githubusercontent.com/102799834/187268103-5c52a94e-24dd-4abf-a07f-71a02099e7c6.png)

**Comment by TheCaduceus** [comment]
DUP if Issue #52.
