### ISSUE TITLE
The gcloner file is missing

### ISSUE THREAD

**Issue by emapps** [TheCaduceus/CloneBot_V2#59]
Hello, what can be done to stop it showing?

> C:\Users\xxx\Desktop\CloneBot_V2>python telegram_gcloner/telegram_gcloner.py
> 2022-08-29 20:36:24,295 - utils.config_loader - INFO - Found telegram_token: 53810xxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 2022-08-29 20:36:24,295 - utils.config_loader - INFO - Found user_ids: xxxxxxxxxxxx
> 2022-08-29 20:36:24,295 - utils.config_loader - INFO - Found group_ids: -1
> 2022-08-29 20:36:24,295 - utils.config_loader - INFO - Found path_to_gclone: gclone.exe
> 2022-08-29 20:36:24,295 - utils.config_loader - INFO - Found gclone_para_override:
> 2022-08-29 20:36:24,315 - utils.config_loader - **WARNING - Gclone Executable was not found in the Drectory.**
> Press Enter to continue...

**Comment by TheCaduceus** [comment]
Read Guide.
