### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by oknchm** [TheCaduceus/CloneBot_V2#60]
I'm trying to deploy CloneBot_V2 via PC but I get an error message `IndentationError: unexpected indent`. I didn't touch any of the .py files so I'm not sure what causes this error. The only one I edited was the `config.ini` file.

Currently using Windows 10 and Python version 3.10.

Hope you can help me. Thank you!

![Screenshot 2022-09-02 070207](https://user-images.githubusercontent.com/86455151/188026792-221b2ca3-a6b3-4465-a12e-53297a2b3ed7.png)

**Comment by TheCaduceus** [comment]
Use `git clone https://github.com/TheCaduceus/CloneBot_V2` to download the repository in your device. This error is caused because @MahamudIBA pushed the commit without even checking it into `v2.2.9` release.
