### ISSUE TITLE
Unable to fetch google drive link

### ISSUE THREAD

**Issue by ubaiidullaah** [TheCaduceus/CloneBot_V2#62]
![image](https://user-images.githubusercontent.com/87019127/188129248-282210f6-dbd8-45e0-a9fc-430d64b4f4a1.png)

**Comment by TheCaduceus** [comment]
@ubaiidullaah Restart the bot and try again! or try after 24 hours.

**Comment by ubaiidullaah** [comment]
@TheCaduceus  Thanks, It is working now.
