### ISSUE TITLE
OSError: [WinError 1392] The file or directory is corrupted and unreadable

### ISSUE THREAD

**Issue by oknchm** [TheCaduceus/CloneBot_V2#65]
Sorry for posting here again but I'm deploying CloneBot_V2 on my PC but I get this error when I try to copy files. Already tried searching on Google to fix the error using sfc, chkdsk, DISM; Also tried re-downloading and reinstalling CloneBot_V2, even Python, and Git on my PC but nothing has worked so far. Thanks in advance.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\[threading.py](http://threading.py/)", line 1016, in _bootstrap_inner
    [self.run](http://self.run/)()
  File "C:\CloneBot_V2\telegram_gcloner\utils\fire_save_files.py", line 95, in run
    process = subprocess.Popen(command_line,
  File "C:\Program Files\Python310\lib\[subprocess.py](http://subprocess.py/)", line 969, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\[subprocess.py](http://subprocess.py/)", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 1392] The file or directory is corrupted and unreadable
```
![Screenshot 2022-09-04 013639](https://user-images.githubusercontent.com/86455151/188504066-5531afc2-b7b2-47b9-85a6-6673b88edab6.png)

![Screenshot 2022-09-04 020038](https://user-images.githubusercontent.com/86455151/188504136-9a6bfd42-c100-41df-9d6b-2b101eebf707.png)

**Comment by TheCaduceus** [comment]
Use `chmod +x gclone` or `chmod +x ./gclone`

**Comment by oknchm** [comment]
For anyone who encounters this same problem, try downloading gclone directly from the link given [here](https://github.com/TheCaduceus/CloneBot_V2#4download-gclone) instead of using curl. The gclone file I downloaded via curl was corrupted even if I chose the right one for my system. Good luck!
