### ISSUE TITLE
About Add SA account to Google Group

### ISSUE THREAD

**Issue by MASSMonarch** [TheCaduceus/CloneBot_V2#67]
What will happened if I add all 100 Email IDs in Google Group rather than10 Email IDs at once ?????

![Capture](https://user-images.githubusercontent.com/113176669/189332682-f8873807-518e-4205-ae15-fcd51a8863a8.JPG)

**Comment by TheCaduceus** [comment]
@MASSMonarch Google will rate limit user's Google Group for 24 hours and user will not be able to add more service accounts or normal user for that period of time.
