### ISSUE TITLE
Unable to clone file

### ISSUE THREAD

**Issue by thefexcos791** [TheCaduceus/CloneBot_V2#69]
Bot can't copy gdrive file but folder working fine. Any solution?
![Screenshot_20220921-070444](https://user-images.githubusercontent.com/108440782/191385972-24b59b76-4bd9-4810-ba9d-368b51f2c5f9.png)

**Comment by TheCaduceus** [comment]
@thefexcos791 Restart bot or check the accounts.zip it should only contain `.json` files not any folder.
