### ISSUE TITLE
any solution is vps on windows

### ISSUE THREAD

**Issue by BragnarXIX** [TheCaduceus/CloneBot_V2#71]
![Sin título](https://user-images.githubusercontent.com/114120494/191635961-982ac588-b20c-4768-8ad4-ff450d4b8974.jpg)
as also the statistics of downloads do not appear and the copy is not made in full

**Comment by TheCaduceus** [comment]
**Newer gclone builds not shows ETA and other statistics of clone process, you can try older builds like [this](https://github.com/MsGsuite/CloneBot/raw/master/telegram_gcloner/gclone.exe) (For Windows) or [this](https://github.com/MsGsuite/CloneBot/raw/master/gclone) (For Linux).**
