### ISSUE TITLE
How to deply in docker or VPS

### ISSUE THREAD

**Issue by ciniexpress** [TheCaduceus/CloneBot_V2#83]
Hello, i have tried the method mentioned in the guide and tried both VPS and Docker, but nothing worked.

1. In docker there is no proper deploy method, please provide how to deploy in docker

2. In vps bot has started but when i try to copy the files it is giving me error like --- PermissionError: [Errno 13] Permission denied: '/root/CloneBot_V2/telegram_gcloner/gclone'

<img width="879" alt="image" src="https://user-images.githubusercontent.com/84844340/200194598-5d3cf336-5a38-4c28-a7d4-b4fd9b78d8d2.png">

help fixing anyone of the issues, thanks

**Comment by TheCaduceus** [comment]
**@ciniexpress Refer to #75**
